### PR TITLE
fix error str path

### PR DESCRIPTION
**Pull request by kxhit**
I encountered the error `argument 1 must be str not posixpath` and fixed it by casting` database_path` to `str`.

### CODE REVIEW

**Comment by Skydes** [comment]
Thanks for the feedback. The issue in pipeline_Aachen.ipynb is indeed a typo. Regarding the casting to str: are you using Python3.5?

**Comment by kxhit** [comment]
Thanks for your reply! I'm using python3.6.10 within anaconda.

**Comment by Skydes** [comment]
Thanks, [that was indeed only fixed in Python 3.7](https://bugs.python.org/issue33496). Could you please revert your second commit? I already fixed it in https://github.com/cvg/Hierarchical-Localization/pull/2 since that was critical. Then I'll happily merge your fix!

**Comment by Skydes** [comment]
Thanks!

**Pull request merged**
