### PR TITLE
replace glob with rglob #283

### LINKED ISSUE #283: pathlib.Path.glob does not follow symlinks
It is [same issue as introduced in cpython](https://github.com/python/cpython/issues/77609). 

Shortly, if there are symlinks under `Path(root)`, `Path(root).glob('**/*')` does not catch all pathnames from symlink. 

So it makes error if user use symlink at datasets and do [extract_features.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/extract_features.py#L179C4-L179C4) 

Solution is simple. Just replace `Path(root).glob('**/'+g)` with `Path(root).rglob('*/'+g)`. 

I'll open pull request for this issue soon.

### PR DESCRIPTION
**Pull request by Keunmo**
PR for fix #283. 

Replace `Path(some_path).glob('**/*')` with `Path(some_path).rglob('*/*')`. 

Act same as original code, and it can also find files from symlink.

### CODE REVIEW

**Comment by Skydes** [comment]
Thanks for sending this PR. Shouldn't the update be
```diff
```

**Comment by Skydes** [comment]
Thanks for sending this PR. The [doc](https://docs.python.org/3/library/pathlib.html#pathlib.Path.rglob) mentions
> This is like calling [Path.glob()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob) with “**/” added in front of the given relative pattern

So shouldn't the update be
```diff
- paths += list(Path(root).glob('**/'+g))
+ paths += list(Path(root).rglob(g))
```
instead of
```diff
- paths += list(Path(root).glob('**/'+g))
+ paths += list(Path(root).rglob('*/'+g))
```
?

**Comment by Keunmo** [comment]
Thanks for reviewing! 

I've tested with several scenarios, and I think current update is more suitable for handling various scenarios involving symlinks.

* Case 1: When dataset path is a symlink, and mapping path and query path are regular directories.
* Case 2: When dataset path is a regular directory, and mapping path and query path are symlinks.
* Case 3: When dataset path, mapping path, and query path are all symlinks.  

In these cases, `paths += list(Path(root).rglob('*/'+g))` worked well for all three cases, but `paths += list(Path(root).rglob(g))` only worked for case 1 and failed for Cases 2 and 3. I think it's because when rglob traversal, if a child directory is a symlink, it does not explore within that symlink directory.

So, I believe current approach is more appropriate.

**Comment by Skydes** [comment]
`Path(root).rglob('*/'+g)` only handles symlinks at the top level, unlike `glob.glob` which handles arbitrary levels. This is exactly what the cpython issue says. Let's instead use glob, as:
```python
paths += glob.glob((Path(root) / '**' / g).as_posix()), recursive=True)
```
Can you please confirms that it works and make the changes? Thanks!

**Comment by Keunmo** [comment]
You're right, `glob.glob` looks better. I changed it to glob, but it returns list with `str`, not `pathlib.PosixPath`. So I convert it to PosixPath like this:
```Python3
paths += list(map(Path, glob.glob((Path(root) / '**' / g).as_posix(), recursive=True)))
```
And it works all good. Thanks!

**Pull request merged**
