### PR TITLE
pass use_pba to mapper to use GPU

### PR DESCRIPTION
**Pull request by oldshuren1**

### CODE REVIEW

**Comment by reynoldscem** [comment]
I've made a similar change locally. It's worth noting that if your problem gets big enough COLMAP will fall-back to the CPU version of PBA which is ~an order of magnitude slower. You can remove the check in COLMAP to always use the GPU if you are comfortable with risking the worse numerical stability.

**Comment by oldshuren1** [comment]
Think you mean in controller/incremental_mapper.cc:68 checking for  ParallelBundleAdjuster::IsSupported?

I also found that if the camera mode is single, pba is also not used. But using single camera itself can reduce a lot of time.

**Comment by reynoldscem** [comment]
No I don’t mean that. There’s a check on the number of residuals in the problem hardcoded. I’ll have a look for it on Monday if you can’t find it.

**Comment by Skydes** [comment]
Since `IncrementalMapperOptions` has many other useful options, I would prefer to instead provide a flexible mechanism to modify any of these options from the command line, just like COLMAP accepts `--Mapper.ba_global_pba_gpu_index 1`. This could be later extended to the `ImageReaderOptions`.

**Comment by Skydes** [comment]
This should be solved by https://github.com/cvg/Hierarchical-Localization/pull/210. Can you please confirm that it works for you?

**Pull request closed without merging**
